version: '3'

vars:
  TEST:
    sh: go list ./... | grep -v 'vendor'
  HOSTNAME: hashicorp.com
  NAMESPACE: 64mb
  NAME: clickhouse
  BINARY: terraform-provider-{{.NAME}}
  VERSION: 0.0.0
  OS_ARCH: linux_amd64
  OS_ARCH_DARWIN: darwin_arm64

tasks:
  test-acc:
    desc: Run acceptance tests
    env:
      TF_ACC: 1
      TF_CLICKHOUSE_HOST: '127.0.0.1'
      TF_CLICKHOUSE_USERNAME: 'default'
      TF_CLICKHOUSE_PASSWORD: ''
      TF_CLICKHOUSE_PORT: 9000
    cmds:
      - go test -tags testing ./... -v {{.TESTARGS}} -timeout 120m

  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BINARY}}

  release:
    desc: Build release binaries for multiple platforms
    cmds:
      - mkdir -p ./bin
      - GOOS=darwin GOARCH=amd64 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_darwin_amd64
      - GOOS=freebsd GOARCH=386 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_freebsd_386
      - GOOS=freebsd GOARCH=amd64 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_freebsd_amd64
      - GOOS=freebsd GOARCH=arm go build -o ./bin/{{.BINARY}}_{{.VERSION}}_freebsd_arm
      - GOOS=linux GOARCH=386 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_linux_386
      - GOOS=linux GOARCH=amd64 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_linux_amd64
      - GOOS=linux GOARCH=arm go build -o ./bin/{{.BINARY}}_{{.VERSION}}_linux_arm
      - GOOS=openbsd GOARCH=386 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_openbsd_386
      - GOOS=openbsd GOARCH=amd64 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_openbsd_amd64
      - GOOS=solaris GOARCH=amd64 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_solaris_amd64
      - GOOS=windows GOARCH=386 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_windows_386
      - GOOS=windows GOARCH=amd64 go build -o ./bin/{{.BINARY}}_{{.VERSION}}_windows_amd64

  install:
    desc: Install the provider for Linux
    deps: [build]
    cmds:
      - mkdir -p ~/.terraform.d/plugins/{{.HOSTNAME}}/{{.NAMESPACE}}/{{.NAME}}/{{.VERSION}}/{{.OS_ARCH}}
      - mv {{.BINARY}} ~/.terraform.d/plugins/{{.HOSTNAME}}/{{.NAMESPACE}}/{{.NAME}}/{{.VERSION}}/{{.OS_ARCH}}

  install-darwin:
    desc: Install the provider for Darwin (macOS)
    deps: [build]
    cmds:
      - mkdir -p ~/.terraform.d/plugins/{{.HOSTNAME}}/{{.NAMESPACE}}/{{.NAME}}/{{.VERSION}}/{{.OS_ARCH_DARWIN}}
      - mv {{.BINARY}} ~/.terraform.d/plugins/{{.HOSTNAME}}/{{.NAMESPACE}}/{{.NAME}}/{{.VERSION}}/{{.OS_ARCH_DARWIN}}

  test:
    desc: Run unit tests
    cmds:
      - go test -i {{.TEST}} || exit 1
      - echo "{{.TEST}}" | xargs -t -n4 go test {{.TESTARGS}} -timeout=30s -parallel=4

  doc:
    desc: Generate documentation
    cmds:
      - go generate ./...
